from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, List
import oracledb

app = FastAPI(title="API Sistema Hospital - Todos los Módulo e Indicadores")

# Configuración de CORS para comunicarse con Angular
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DB_USER = "system"
DB_PASSWORD = "AdminHospital123!"
DB_DSN = "hospital_db:1521/FREE"

def get_connection():
    return oracledb.connect(user=DB_USER, password=DB_PASSWORD, dsn=DB_DSN)

def registrar_auditoria(cursor, usuario: str, accion: str, tabla_afectada: str, detalle: str):
    """Función auxiliar para registrar logs de auditoría en Oracle"""
    try:
        cursor.execute("""
            INSERT INTO bitacora_auditoria (usuario, accion, tabla_afectada, detalle, fecha_hora)
            VALUES (:1, :2, :3, :4, SYSTIMESTAMP)
        """, [usuario, accion, tabla_afectada, detalle])
    except Exception as e:
        print(f"Error registrando auditoría: {e}")

# ==========================================
# MODELOS DE DATOS (PYDANTIC SCHEMAS)
# ==========================================

class ResponsableSchema(BaseModel):
    nombre_completo: str
    dpi: str
    telefono: str

class PacienteSchema(BaseModel):
    nombre_completo: str
    dpi_documento: str
    fecha_nacimiento: str  # YYYY-MM-DD
    telefono: str
    correo: str
    id_responsable: Optional[int] = None

class MedicoSchema(BaseModel):
    nombre_completo: str
    colegiado_numero: str
    especialidad: str
    firma_digital_hash: Optional[str] = "HASH_DEFAULT"

class JornadaMedicoSchema(BaseModel):
    id_medico: int
    dia_semana: str  # LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO
    hora_inicio: str # HH24:MI (ej: 08:00)
    hora_fin: str    # HH24:MI (ej: 16:00)

class CitaSchema(BaseModel):
    fecha_hora: str  # YYYY-MM-DD HH24:MI
    id_paciente: int
    id_medico: int
    estado: Optional[str] = "Programada"

class ExpedienteSchema(BaseModel):
    id_paciente: int
    id_medico: int

class MedicamentoSchema(BaseModel):
    nombre_comercial: str
    stock_disponible: int
    precio_unitario: float

class RecetaSchema(BaseModel):
    id_expediente: int
    id_medico: int
    fecha_vencimiento: str  # YYYY-MM-DD
    estado: Optional[str] = "Vigente"
    id_medicamento: int  # Para ligar a detalle_receta

class LaboratorioExternoSchema(BaseModel):
    nombre_laboratorio: str

class ResultadoLabSchema(BaseModel):
    id_expediente: int
    id_laboratorio: int
    tipo_examen: str
    pdf_url: Optional[str] = "http://localhost:8080/reporte.pdf"
    es_critico: int  # 1 para crítico, 0 para normal

class ImagenMedicaSchema(BaseModel):
    id_expediente: int
    modalidad: str  # RX, TAC, RMN, US
    dicom_url: Optional[str] = "http://localhost:8080/estudio.dcm"
    observaciones: Optional[str] = "Estudio sin novedades"

class FacturaSchema(BaseModel):
    id_paciente: int
    monto_total: float
    estado: Optional[str] = "Pendiente"


@app.get("/")
def read_root():
    return {"mensaje": "Backend Sistema Hospitalario Operativo"}


# ==========================================
# 1. INICIALIZACIÓN DE BASE DE DATOS
# ==========================================
@app.post("/init-db")
def inicializar_base_datos_completa():
    conn = get_connection()
    cursor = conn.cursor()

    tablas_sql = [
        """CREATE TABLE responsable_legal (
            id_responsable NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre_completo VARCHAR2(150),
            dpi VARCHAR2(20),
            telefono VARCHAR2(15)
        )""",
        """CREATE TABLE medico (
            id_medico NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre_completo VARCHAR2(150),
            colegiado_numero VARCHAR2(20),
            especialidad VARCHAR2(100),
            firma_digital_hash VARCHAR2(255)
        )""",
        """CREATE TABLE jornada_medico (
            id_jornada NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_medico NUMBER,
            dia_semana VARCHAR2(20),
            hora_inicio VARCHAR2(5),
            hora_fin VARCHAR2(5),
            CONSTRAINT fk_jornada_medico FOREIGN KEY (id_medico) REFERENCES medico(id_medico) ON DELETE CASCADE
        )""",
        """CREATE TABLE medicamento (
            id_medicamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre_comercial VARCHAR2(150),
            stock_disponible NUMBER,
            precio_unitario NUMBER(10,2)
        )""",
        """CREATE TABLE laboratorio_externo (
            id_laboratorio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre_laboratorio VARCHAR2(150)
        )""",
        """CREATE TABLE paciente (
            id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre_completo VARCHAR2(150),
            dpi_documento VARCHAR2(20),
            fecha_nacimiento DATE,
            telefono VARCHAR2(15),
            correo VARCHAR2(100),
            id_responsable NUMBER,
            CONSTRAINT fk_paciente_resp FOREIGN KEY (id_responsable) REFERENCES responsable_legal(id_responsable)
        )""",
        """CREATE TABLE cita (
            id_cita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fecha_hora TIMESTAMP,
            id_paciente NUMBER,
            id_medico NUMBER,
            estado VARCHAR2(50),
            CONSTRAINT fk_cita_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente),
            CONSTRAINT fk_cita_medico FOREIGN KEY (id_medico) REFERENCES medico(id_medico)
        )""",
        """CREATE TABLE factura (
            id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_paciente NUMBER,
            monto_total NUMBER(10,2),
            estado VARCHAR2(50),
            fecha_emision TIMESTAMP,
            CONSTRAINT fk_factura_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente)
        )""",
        """CREATE TABLE expediente_clinico (
            id_expediente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_paciente NUMBER,
            id_medico NUMBER,
            fecha_consulta TIMESTAMP,
            CONSTRAINT fk_exp_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente),
            CONSTRAINT fk_exp_medico FOREIGN KEY (id_medico) REFERENCES medico(id_medico)
        )""",
        """CREATE TABLE receta_medica (
            id_receta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_expediente NUMBER,
            id_medico NUMBER,
            fecha_emision DATE,
            fecha_vencimiento DATE,
            estado VARCHAR2(50),
            CONSTRAINT fk_receta_exp FOREIGN KEY (id_expediente) REFERENCES expediente_clinico(id_expediente),
            CONSTRAINT fk_receta_med FOREIGN KEY (id_medico) REFERENCES medico(id_medico)
        )""",
        """CREATE TABLE resultado_laboratorio (
            id_resultado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_expediente NUMBER,
            id_laboratorio NUMBER,
            tipo_examen VARCHAR2(100),
            pdf_url VARCHAR2(255),
            es_critico NUMBER(1),
            fecha_recepcion TIMESTAMP,
            CONSTRAINT fk_res_exp FOREIGN KEY (id_expediente) REFERENCES expediente_clinico(id_expediente),
            CONSTRAINT fk_res_lab FOREIGN KEY (id_laboratorio) REFERENCES laboratorio_externo(id_laboratorio)
        )""",
        """CREATE TABLE detalle_receta (
            id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_receta NUMBER,
            id_medicamento NUMBER,
            CONSTRAINT fk_detalle_rec FOREIGN KEY (id_receta) REFERENCES receta_medica(id_receta),
            CONSTRAINT fk_detalle_med FOREIGN KEY (id_medicamento) REFERENCES medicamento(id_medicamento)
        )""",
        """CREATE TABLE imagen_medica (
            id_imagen NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_expediente NUMBER,
            modalidad VARCHAR2(20),
            dicom_url VARCHAR2(255),
            observaciones VARCHAR2(500),
            fecha_estudio TIMESTAMP,
            CONSTRAINT fk_img_exp FOREIGN KEY (id_expediente) REFERENCES expediente_clinico(id_expediente)
        )""",
        """CREATE TABLE bitacora_auditoria (
            id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario VARCHAR2(50),
            accion VARCHAR2(100),
            tabla_afectada VARCHAR2(50),
            detalle VARCHAR2(500),
            fecha_hora TIMESTAMP
        )"""
    ]

    errores = []
    tablas_creadas = 0

    for sql in tablas_sql:
        try:
            cursor.execute(sql)
            tablas_creadas += 1
        except oracledb.DatabaseError as e:
            error_obj, = e.args
            if error_obj.code != 955: # Tabla ya existente
                errores.append(str(error_obj.message))

    conn.commit()
    conn.close()

    if errores:
        return {"status": "advertencia", "errores": errores, "tablas_creadas": tablas_creadas}
    
    return {"status": "ok", "mensaje": "Estructura completa de tablas e indicadores inicializada en Oracle DB"}


# ==========================================
# 2. MÓDULO DE PACIENTES Y RESPONSABLE LEGAL
# ==========================================
@app.get("/pacientes")
def obtener_pacientes():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT p.id_paciente, p.nombre_completo, p.dpi_documento, 
               TO_CHAR(p.fecha_nacimiento, 'YYYY-MM-DD'), p.telefono, p.correo,
               NVL(r.nombre_completo, 'N/A') AS responsable
        FROM paciente p
        LEFT JOIN responsable_legal r ON p.id_responsable = r.id_responsable
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{
        "id_paciente": f[0], "nombre_completo": f[1], "dpi_documento": f[2],
        "fecha_nacimiento": f[3], "telefono": f[4], "correo": f[5], "responsable": f[6]
    } for f in filas]

@app.post("/pacientes")
def crear_paciente(paciente: PacienteSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO paciente (nombre_completo, dpi_documento, fecha_nacimiento, telefono, correo, id_responsable)
        VALUES (:1, :2, TO_DATE(:3, 'YYYY-MM-DD'), :4, :5, :6)
    """, [paciente.nombre_completo, paciente.dpi_documento, paciente.fecha_nacimiento, paciente.telefono, paciente.correo, paciente.id_responsable])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_PACIENTE", "paciente", f"Paciente {paciente.nombre_completo} registrado")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Paciente registrado correctamente"}

@app.post("/responsables")
def crear_responsable(resp: ResponsableSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO responsable_legal (nombre_completo, dpi, telefono)
        VALUES (:1, :2, :3)
    """, [resp.nombre_completo, resp.dpi, resp.telefono])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_RESPONSABLE", "responsable_legal", f"Responsable {resp.nombre_completo} registrado")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Responsable Legal registrado"}


# ==========================================
# 3. MÓDULO DE MÉDICOS Y JORNADAS
# ==========================================
@app.get("/medicos")
def obtener_medicos():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id_medico, nombre_completo, colegiado_numero, especialidad FROM medico")
    filas = cursor.fetchall()
    conn.close()
    return [{
        "id_medico": f[0], "nombre_completo": f[1], "colegiado_numero": f[2], "especialidad": f[3]
    } for f in filas]

@app.post("/medicos")
def crear_medico(medico: MedicoSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO medico (nombre_completo, colegiado_numero, especialidad, firma_digital_hash)
        VALUES (:1, :2, :3, :4)
    """, [medico.nombre_completo, medico.colegiado_numero, medico.especialidad, medico.firma_digital_hash])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_MEDICO", "medico", f"Médico {medico.nombre_completo} registrado")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Médico registrado correctamente"}

@app.get("/jornadas-medicas")
def obtener_jornadas():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT j.id_jornada, m.nombre_completo, j.dia_semana, j.hora_inicio, j.hora_fin
        FROM jornada_medico j
        JOIN medico m ON j.id_medico = m.id_medico
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{"id_jornada": f[0], "medico": f[1], "dia_semana": f[2], "hora_inicio": f[3], "hora_fin": f[4]} for f in filas]

@app.post("/jornadas-medicas")
def asignar_jornada(jornada: JornadaMedicoSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO jornada_medico (id_medico, dia_semana, hora_inicio, hora_fin)
        VALUES (:1, UPPER(:2), :3, :4)
    """, [jornada.id_medico, jornada.dia_semana, jornada.hora_inicio, jornada.hora_fin])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_JORNADA", "jornada_medico", f"Jornada asignada al médico #{jornada.id_medico}")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Jornada laboral del médico asignada con éxito"}


# ==========================================
# 4. MÓDULO DE CITAS (CON REGLA RN-02 Y DISPONIBILIDAD)
# ==========================================
@app.get("/citas")
def obtener_citas():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT c.id_cita, TO_CHAR(c.fecha_hora, 'YYYY-MM-DD HH24:MI'), 
               p.nombre_completo, m.nombre_completo, c.estado
        FROM cita c
        JOIN paciente p ON c.id_paciente = p.id_paciente
        JOIN medico m ON c.id_medico = m.id_medico
        ORDER BY c.fecha_hora DESC
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{"id_cita": f[0], "fecha_hora": f[1], "paciente": f[2], "medico": f[3], "estado": f[4]} for f in filas]

@app.post("/citas")
def crear_cita(cita: CitaSchema):
    conn = get_connection()
    cursor = conn.cursor()
    
    # 1. Validar RN-02: Conflicto de horario con el médico
    cursor.execute("""
        SELECT COUNT(*) FROM cita 
        WHERE id_medico = :1 
        AND fecha_hora = TO_TIMESTAMP(:2, 'YYYY-MM-DD"T"HH24:MI')
        AND estado != 'Cancelada'
    """, [cita.id_medico, cita.fecha_hora])
    
    if cursor.fetchone()[0] > 0:
        conn.close()
        raise HTTPException(status_code=400, detail="RN-02: El especialista ya posee una cita agendada en este horario exacto.")

    # 2. Validación de Jornada Laboral (Si el médico tiene jornadas definidas)
    cursor.execute("SELECT COUNT(*) FROM jornada_medico WHERE id_medico = :1", [cita.id_medico])
    tiene_jornadas = cursor.fetchone()[0]
    
    if tiene_jornadas > 0:
        cursor.execute("""
            SELECT COUNT(*) FROM jornada_medico
            WHERE id_medico = :1
            AND dia_semana = TRIM(TO_CHAR(TO_TIMESTAMP(:2, 'YYYY-MM-DD"T"HH24:MI'), 'DAY', 'NLS_DATE_LANGUAGE=SPANISH'))
            AND TO_CHAR(TO_TIMESTAMP(:2, 'YYYY-MM-DD"T"HH24:MI'), 'HH24:MI') BETWEEN hora_inicio AND hora_fin
        """, [cita.id_medico, cita.fecha_hora])
        
        if cursor.fetchone()[0] == 0:
            conn.close()
            raise HTTPException(status_code=400, detail="El horario seleccionado está fuera de la jornada médica configurada para este especialista.")

    cursor.execute("""
        INSERT INTO cita (fecha_hora, id_paciente, id_medico, estado)
        VALUES (TO_TIMESTAMP(:1, 'YYYY-MM-DD"T"HH24:MI'), :2, :3, :4)
    """, [cita.fecha_hora, cita.id_paciente, cita.id_medico, cita.estado])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_CITA", "cita", f"Cita programada para Paciente #{cita.id_paciente} con Médico #{cita.id_medico}")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Cita agendada exitosamente"}


# ==========================================
# 5. MÓDULO DE EXPEDIENTE CLÍNICO Y RADIOLOGÍA
# ==========================================
@app.get("/expedientes")
def obtener_expedientes():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT e.id_expediente, p.nombre_completo, m.nombre_completo, 
               TO_CHAR(e.fecha_consulta, 'YYYY-MM-DD HH24:MI')
        FROM expediente_clinico e
        JOIN paciente p ON e.id_paciente = p.id_paciente
        JOIN medico m ON e.id_medico = m.id_medico
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{"id_expediente": f[0], "paciente": f[1], "medico": f[2], "fecha_consulta": f[3]} for f in filas]

@app.post("/expedientes")
def crear_expediente(exp: ExpedienteSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO expediente_clinico (id_paciente, id_medico, fecha_consulta)
        VALUES (:1, :2, SYSTIMESTAMP)
    """, [exp.id_paciente, exp.id_medico])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_EXPEDIENTE", "expediente_clinico", f"Expediente aperturado para paciente #{exp.id_paciente}")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Expediente clínico aperturado"}

@app.get("/imagenes-medicas")
def obtener_imagenes_medicas():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT i.id_imagen, i.id_expediente, i.modalidad, i.dicom_url, i.observaciones,
               TO_CHAR(i.fecha_estudio, 'YYYY-MM-DD HH24:MI')
        FROM imagen_medica i
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{
        "id_imagen": f[0], "id_expediente": f[1], "modalidad": f[2],
        "dicom_url": f[3], "observaciones": f[4], "fecha_estudio": f[5]
    } for f in filas]

@app.post("/imagenes-medicas")
def registrar_imagen_medica(img: ImagenMedicaSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO imagen_medica (id_expediente, modalidad, dicom_url, observaciones, fecha_estudio)
        VALUES (:1, :2, :3, :4, SYSTIMESTAMP)
    """, [img.id_expediente, img.modalidad, img.dicom_url, img.observaciones])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_IMAGEN_MEDICA", "imagen_medica", f"Estudio radiológico {img.modalidad} adjuntado al expediente #{img.id_expediente}")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Estudio radiológico/DICOM adjuntado al expediente"}


# ==========================================
# 6. MÓDULO DE FARMACIA Y MEDICAMENTOS
# ==========================================
@app.get("/medicamentos")
def obtener_medicamentos():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id_medicamento, nombre_comercial, stock_disponible, precio_unitario FROM medicamento")
    filas = cursor.fetchall()
    conn.close()
    return [{"id_medicamento": f[0], "nombre_comercial": f[1], "stock_disponible": f[2], "precio_unitario": f[3]} for f in filas]

@app.post("/medicamentos")
def crear_medicamento(med: MedicamentoSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO medicamento (nombre_comercial, stock_disponible, precio_unitario)
        VALUES (:1, :2, :3)
    """, [med.nombre_comercial, med.stock_disponible, med.precio_unitario])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_MEDICAMENTO", "medicamento", f"Medicamento {med.nombre_comercial} registrado")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Medicamento registrado en inventario"}


# ==========================================
# 7. MÓDULO DE RECETAS MÉDICAS
# ==========================================
@app.get("/recetas")
def obtener_recetas():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT r.id_receta, r.id_expediente, m.nombre_completo, 
               TO_CHAR(r.fecha_emision, 'YYYY-MM-DD'), TO_CHAR(r.fecha_vencimiento, 'YYYY-MM-DD'), r.estado
        FROM receta_medica r
        JOIN medico m ON r.id_medico = m.id_medico
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{"id_receta": f[0], "id_expediente": f[1], "medico": f[2], "fecha_emision": f[3], "fecha_vencimiento": f[4], "estado": f[5]} for f in filas]

@app.post("/recetas")
def crear_receta(receta: RecetaSchema):
    conn = get_connection()
    cursor = conn.cursor()
    
    # 1. Crear Receta
    out_id = cursor.var(oracledb.NUMBER)
    cursor.execute("""
        INSERT INTO receta_medica (id_expediente, id_medico, fecha_emision, fecha_vencimiento, estado)
        VALUES (:1, :2, SYSDATE, TO_DATE(:3, 'YYYY-MM-DD'), :4)
        RETURNING id_receta INTO :5
    """, [receta.id_expediente, receta.id_medico, receta.fecha_vencimiento, receta.estado, out_id])
    
    id_receta_creada = out_id.getvalue()[0]
    
    # 2. Registrar en Detalle Receta
    cursor.execute("""
        INSERT INTO detalle_receta (id_receta, id_medicamento)
        VALUES (:1, :2)
    """, [id_receta_creada, receta.id_medicamento])
    
    # 3. Descontar Stock de Medicamento
    cursor.execute("""
        UPDATE medicamento 
        SET stock_disponible = stock_disponible - 1 
        WHERE id_medicamento = :1 AND stock_disponible > 0
    """, [receta.id_medicamento])

    registrar_auditoria(cursor, "MÉDICO", "EMITIR_RECETA", "receta_medica", f"Receta #{id_receta_creada} emitida con firma digital hash")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": f"Receta #{id_receta_creada} emitida y firmada digitalmente"}


# ==========================================
# 8. MÓDULO DE LABORATORIO
# ==========================================
@app.post("/laboratorios-externos")
def crear_laboratorio_externo(lab: LaboratorioExternoSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT INTO laboratorio_externo (nombre_laboratorio) VALUES (:1)", [lab.nombre_laboratorio])
    
    registrar_auditoria(cursor, "SISTEMA", "CREAR_LABORATORIO", "laboratorio_externo", f"Laboratorio {lab.nombre_laboratorio} registrado")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Laboratorio externo registrado"}

@app.get("/resultados-laboratorio")
def obtener_resultados():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT r.id_resultado, r.id_expediente, l.nombre_laboratorio, r.tipo_examen, 
               r.pdf_url, r.es_critico, TO_CHAR(r.fecha_recepcion, 'YYYY-MM-DD HH24:MI')
        FROM resultado_laboratorio r
        JOIN laboratorio_externo l ON r.id_laboratorio = l.id_laboratorio
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{
        "id_resultado": f[0], "id_expediente": f[1], "laboratorio": f[2],
        "tipo_examen": f[3], "pdf_url": f[4], "es_critico": f[5], "fecha_recepcion": f[6]
    } for f in filas]

@app.post("/resultados-laboratorio")
def registrar_resultado_lab(res: ResultadoLabSchema):
    conn = get_connection()
    cursor = conn.cursor()
    
    try:
        cursor.execute("SELECT COUNT(*) FROM laboratorio_externo WHERE id_laboratorio = :1", [res.id_laboratorio])
        existe_lab = cursor.fetchone()[0]
        
        if existe_lab == 0:
            cursor.execute("""
                INSERT INTO laboratorio_externo (id_laboratorio, nombre_laboratorio) 
                VALUES (:1, 'Laboratorio Central Hospitalario')
            """, [res.id_laboratorio])

        es_critico_val = int(res.es_critico)

        cursor.execute("""
            INSERT INTO resultado_laboratorio (id_expediente, id_laboratorio, tipo_examen, pdf_url, es_critico, fecha_recepcion)
            VALUES (:1, :2, :3, :4, :5, SYSTIMESTAMP)
        """, [res.id_expediente, res.id_laboratorio, res.tipo_examen, res.pdf_url, es_critico_val])
        
        registrar_auditoria(cursor, "LABORATORIO", "REGISTRAR_RESULTADO", "resultado_laboratorio", f"Examen {res.tipo_examen} registrado. Crítico: {es_critico_val}")
        
        conn.commit()
        conn.close()

        alerta = "⚠️ ALERTA CRÍTICA (RF-19): Se ha notificado al médico tratante sobre este examen." if es_critico_val == 1 else "Resultado de laboratorio registrado con éxito."
        return {"status": "ok", "mensaje": alerta}

    except Exception as e:
        conn.close()
        print(f"Error en Laboratorio: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Error en BD: {str(e)}")


# ==========================================
# 9. MÓDULO DE FACTURACIÓN Y REPORTES KPI
# ==========================================
@app.get("/facturas")
def obtener_facturas():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT f.id_factura, p.nombre_completo, f.monto_total, f.estado, 
               TO_CHAR(f.fecha_emision, 'YYYY-MM-DD HH24:MI')
        FROM factura f
        JOIN paciente p ON f.id_paciente = p.id_paciente
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{"id_factura": f[0], "paciente": f[1], "monto_total": f[2], "estado": f[3], "fecha_emision": f[4]} for f in filas]

@app.post("/facturas")
def crear_factura(fac: FacturaSchema):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO factura (id_paciente, monto_total, estado, fecha_emision)
        VALUES (:1, :2, :3, SYSTIMESTAMP)
    """, [fac.id_paciente, fac.monto_total, fac.estado])
    
    registrar_auditoria(cursor, "SISTEMA", "EMITIR_FACTURA", "factura", f"Factura por Q.{fac.monto_total} emitida para paciente #{fac.id_paciente}")
    conn.commit()
    conn.close()
    return {"status": "ok", "mensaje": "Factura generada exitosamente"}

@app.get("/reportes/kpis")
def obtener_kpis():
    """Consolida las métricas e indicadores de rendimiento hospitalario"""
    conn = get_connection()
    cursor = conn.cursor()
    
    cursor.execute("SELECT NVL(SUM(monto_total), 0) FROM factura WHERE estado = 'Pagada' OR estado = 'Pendiente'")
    total_ingresos = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM cita")
    total_citas = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM receta_medica WHERE estado = 'Vigente'")
    recetas_vigentes = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM resultado_laboratorio WHERE es_critico = 1")
    examenes_criticos = cursor.fetchone()[0]
    
    conn.close()
    
    return {
        "ingresos_totales": total_ingresos,
        "total_citas": total_citas,
        "recetas_vigentes": recetas_vigentes,
        "examenes_criticos": examenes_criticos
    }

@app.get("/bitacora")
def obtener_bitacora():
    """Consulta los registros de la bitácora de auditoría"""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT id_log, usuario, accion, tabla_afectada, detalle, TO_CHAR(fecha_hora, 'YYYY-MM-DD HH24:MI:SS')
        FROM bitacora_auditoria
        ORDER BY fecha_hora DESC
    """)
    filas = cursor.fetchall()
    conn.close()
    return [{
        "id_log": f[0], "usuario": f[1], "accion": f[2],
        "tabla_afectada": f[3], "detalle": f[4], "fecha_hora": f[5]
    } for f in filas]


# ==========================================
# ELIMINAR REGISTROS
# ==========================================
@app.delete("/medicos/{id_medico}")
def eliminar_medico(id_medico: int):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM medico WHERE id_medico = :1", [id_medico])
        registrar_auditoria(cursor, "SISTEMA", "ELIMINAR_MEDICO", "medico", f"Médico #{id_medico} eliminado")
        conn.commit()
        conn.close()
        return {"status": "ok", "mensaje": "Médico eliminado correctamente"}
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=400, detail="No se puede eliminar el médico porque tiene citas o registros vinculados.")

@app.delete("/pacientes/{id_paciente}")
def eliminar_paciente(id_paciente: int):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM paciente WHERE id_paciente = :1", [id_paciente])
        registrar_auditoria(cursor, "SISTEMA", "ELIMINAR_PACIENTE", "paciente", f"Paciente #{id_paciente} eliminado")
        conn.commit()
        conn.close()
        return {"status": "ok", "mensaje": "Paciente eliminado correctamente"}
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=400, detail="No se puede eliminar el paciente porque tiene expediente, citas o facturas vinculadas.")

@app.delete("/citas/{id_cita}")
def eliminar_cita(id_cita: int):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM cita WHERE id_cita = :1", [id_cita])
        registrar_auditoria(cursor, "SISTEMA", "ELIMINAR_CITA", "cita", f"Cita #{id_cita} eliminada")
        conn.commit()
        conn.close()
        return {"status": "ok", "mensaje": "Cita eliminada"}
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=400, detail="No se pudo eliminar la cita.")

@app.delete("/expedientes/{id_expediente}")
def eliminar_expediente(id_expediente: int):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM expediente_clinico WHERE id_expediente = :1", [id_expediente])
        registrar_auditoria(cursor, "SISTEMA", "ELIMINAR_EXPEDIENTE", "expediente_clinico", f"Expediente #{id_expediente} eliminado")
        conn.commit()
        conn.close()
        return {"status": "ok", "mensaje": "Expediente eliminado"}
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=400, detail="No se puede eliminar el expediente si tiene recetas o exámenes vinculados.")

@app.delete("/medicamentos/{id_medicamento}")
def eliminar_medicamento(id_medicamento: int):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM medicamento WHERE id_medicamento = :1", [id_medicamento])
        registrar_auditoria(cursor, "SISTEMA", "ELIMINAR_MEDICAMENTO", "medicamento", f"Medicamento #{id_medicamento} eliminado")
        conn.commit()
        conn.close()
        return {"status": "ok", "mensaje": "Medicamento eliminado"}
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=400, detail="No se puede eliminar el medicamento porque está en recetas emitidas.")

@app.delete("/resultados-laboratorio/{id_resultado}")
def eliminar_resultado_lab(id_resultado: int):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM resultado_laboratorio WHERE id_resultado = :1", [id_resultado])
        registrar_auditoria(cursor, "SISTEMA", "ELIMINAR_RESULTADO_LAB", "resultado_laboratorio", f"Resultado #{id_resultado} eliminado")
        conn.commit()
        conn.close()
        return {"status": "ok", "mensaje": "Resultado de laboratorio eliminado"}
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=400, detail="No se pudo eliminar el resultado.")

@app.delete("/facturas/{id_factura}")
def eliminar_factura(id_factura: int):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM factura WHERE id_factura = :1", [id_factura])
        registrar_auditoria(cursor, "SISTEMA", "ELIMINAR_FACTURA", "factura", f"Factura #{id_factura} eliminada")
        conn.commit()
        conn.close()
        return {"status": "ok", "mensaje": "Factura eliminada"}
    except Exception as e:
        conn.close()
        raise HTTPException(status_code=400, detail="No se pudo eliminar la factura.")